version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules  # Avoid overwriting node_modules with host
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development